apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: sre-app
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:endpoint} latency=%{NUMBER:latency:int}ms" }
      }
      date {
        match => [ "timestamp", "ISO8601" ]
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "app-logs-%{+YYYY.MM.dd}"
      }
    }