apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-pleno-app
  namespace: sre-app
  labels:
    app: sre-pleno-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-pleno-app
  template:
    metadata:
      labels:
        app: sre-pleno-app
    spec:
      containers:
      - name: app
        image: sre-pleno-app:v1  # Certifique-se de que deu o build com essa tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        
        # Configuração de Logs para o Filebeat (Volume Mount)
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs

        # Ajuste de Recursos para evitar OOMKilled
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"

        # Health Checks (Baseados no seu código Flask)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: app-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sre-pleno-app-service
  namespace: sre-app
spec:
  selector:
    app: sre-pleno-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP