apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sre-pleno-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-pleno-app
  minReplicas: 2 # Requisito mínimo
  maxReplicas: 5
  metrics:
    # Requisito: Autoscaling baseado em CPU > 70%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Requisito: Autoscaling baseado em memória > 75%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75